language: ruby
rvm:
- 2.4.0

script: ./script/ci

branches:
  only:
    - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

sudo: false # route your build to the container-based infrastructure for a faster build
