# Setup
title:               James' Blog
tagline:             A place for my thoughts
description:         I'm a Software Engineer working at Square, and here's where I put my medium-long term
                     reflections.
url:                 http://jameschang.io
paginate:            1
permalink:           pretty

author:
  name:              James Chang

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
